# Generated by Django 5.1.1 on 2024-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_submission_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java')], default='Python', max_length=10),
        ),
    ]
