# Generated by Django 5.1.1 on 2025-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_assignment_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default='static/courses/default.png', upload_to='courses'),
        ),
    ]
